import adsk.core
import adsk.fusion
import os
import traceback
import json
import hmac
import logging
import logging.handlers
import math
import time
import threading
from pathlib import Path

app = None
ui = None
_stop_event = threading.Event()
monitor_thread = None
custom_event = None
custom_event_handler = None

COMM_DIR = Path.home() / "fusion_mcp_comm"
CUSTOM_EVENT_ID = "FusionMCPCommandEvent"

# Structured logging to file (visible outside Fusion 360's embedded Python)
logger = logging.getLogger("FusionMCP")
logger.setLevel(logging.DEBUG)
_log_file = COMM_DIR / "addin.log"
try:
    COMM_DIR.mkdir(mode=0o700, exist_ok=True)
    _handler = logging.handlers.RotatingFileHandler(str(_log_file), maxBytes=1_000_000, backupCount=3)
    _handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s %(message)s"))
    logger.addHandler(_handler)
except Exception:
    pass  # Logging is best-effort; don't block add-in startup

# Thread-safe storage for pending commands: {command_id: command_dict}
_pending_commands = {}
_pending_lock = threading.Lock()

# Session token read from COMM_DIR/session_token at startup
_session_token = None


def write_error_response(command_id, error_msg):
    """Write an error response file so the MCP server doesn't hang at the 45s timeout."""
    try:
        resp_file = COMM_DIR / f"response_{command_id}.json"
        tmp_file = COMM_DIR / f"response_{command_id}.tmp"
        fd = os.open(str(tmp_file), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        try:
            os.write(fd, json.dumps({"success": False, "error": str(error_msg)}).encode())
        finally:
            os.close(fd)
        os.replace(tmp_file, resp_file)
    except Exception:
        logger.exception("Failed to write error response for command %s", command_id)


class CommandEventHandler(adsk.core.CustomEventHandler):
    """Handles command execution on the main thread via CustomEvent dispatch."""

    def __init__(self):
        super().__init__()

    def notify(self, args):
        command_id = None
        try:
            event_args = adsk.core.CustomEventArgs.cast(args)
            command_id = event_args.additionalInfo

            with _pending_lock:
                command = _pending_commands.pop(command_id, None)

            if command is None:
                return

            result = execute_command(command)
            resp_file = COMM_DIR / f"response_{command_id}.json"
            tmp_file = COMM_DIR / f"response_{command_id}.tmp"
            fd = os.open(str(tmp_file), os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
            try:
                os.write(fd, json.dumps(result).encode())
            finally:
                os.close(fd)
            os.replace(tmp_file, resp_file)
        except Exception as e:
            logger.exception("Event handler error for command %s", command_id)
            if command_id:
                write_error_response(command_id, f"Event handler error: {e}")


def _load_session_token():
    """Load session token from COMM_DIR/session_token."""
    global _session_token
    token_path = COMM_DIR / "session_token"
    try:
        if token_path.exists():
            _session_token = token_path.read_text().strip()
    except Exception:
        logger.exception("Failed to load session token from %s", token_path)
        _session_token = None


def run(context):
    global app, ui, monitor_thread, custom_event, custom_event_handler
    try:
        app = adsk.core.Application.get()
        ui = app.userInterface
        COMM_DIR.mkdir(mode=0o700, exist_ok=True)
        os.chmod(COMM_DIR, 0o700)
        _stop_event.clear()

        # Load session token generated by the MCP server
        _load_session_token()

        # Register custom event for main-thread dispatch
        custom_event = app.registerCustomEvent(CUSTOM_EVENT_ID)
        custom_event_handler = CommandEventHandler()
        custom_event.add(custom_event_handler)

        monitor_thread = threading.Thread(target=monitor_commands, daemon=True)
        monitor_thread.start()
        ui.messageBox("Fusion MCP Started!\n\nListening at:\n" + str(COMM_DIR))
    except Exception:
        if ui:
            ui.messageBox("Failed:\n" + traceback.format_exc())


def stop(context):
    global ui, custom_event, custom_event_handler, monitor_thread
    try:
        _stop_event.set()
        if monitor_thread and monitor_thread.is_alive():
            monitor_thread.join(timeout=1.0)
        if custom_event and custom_event_handler:
            custom_event.remove(custom_event_handler)
        if app:
            app.unregisterCustomEvent(CUSTOM_EVENT_ID)
        if ui:
            ui.messageBox("Fusion MCP Stopped")
    except Exception:
        logger.exception("Error during add-in stop")


def _handle_cmd_error(cmd_file, error_msg):
    """Handle a failed command: write error response and clean up the command file."""
    cmd_id = cmd_file.stem.removeprefix("command_")
    write_error_response(cmd_id, error_msg)
    try:
        cmd_file.unlink()
    except Exception:
        pass


def monitor_commands():
    """Background thread: watches for command files, dispatches to main thread via CustomEvent."""
    dispatched_ids = {}  # command_id -> dispatch_time (for TTL-based cleanup)
    while not _stop_event.is_set():
        try:
            # TTL cleanup: remove entries older than 60s to prevent unbounded growth
            now = time.monotonic()
            expired = [cid for cid, t in dispatched_ids.items() if now - t > 60]
            for cid in expired:
                dispatched_ids.pop(cid, None)

            cmd_files = list(COMM_DIR.glob("command_*.json"))
            for cmd_file in cmd_files:
                try:
                    with open(cmd_file, "r") as f:
                        command = json.load(f)

                    command_id = str(command.get("id", ""))
                    if not command_id:
                        _handle_cmd_error(cmd_file, "Command missing 'id' field")
                        continue

                    # Session token validation (MT-3) — reject if token loaded but mismatched
                    if _session_token is not None:
                        cmd_token = command.get("session_token", "")
                        if not hmac.compare_digest(cmd_token.encode(), _session_token.encode()):
                            # Token mismatch — re-read in case MCP server restarted with new token
                            _load_session_token()
                            if _session_token is not None and hmac.compare_digest(cmd_token.encode(), _session_token.encode()):
                                pass  # Token refreshed and now matches — continue processing
                            else:
                                logger.warning("Session token mismatch for command %s", command_id)
                                _handle_cmd_error(cmd_file, "Invalid or missing session token")
                                continue
                    else:
                        # Token not loaded — reject commands for security
                        logger.warning("Session token not loaded — rejecting command %s", command_id)
                        _handle_cmd_error(cmd_file, "Session token not loaded — restart add-in after MCP server")
                        continue

                    # Skip if already dispatched (file deletion may have failed)
                    if command_id in dispatched_ids:
                        continue

                    # Stash command for main-thread handler, then fire event
                    with _pending_lock:
                        _pending_commands[command_id] = command

                    app.fireCustomEvent(CUSTOM_EVENT_ID, command_id)
                    dispatched_ids[command_id] = time.monotonic()

                    try:
                        cmd_file.unlink()
                    except Exception:
                        pass

                except json.JSONDecodeError as e:
                    _handle_cmd_error(cmd_file, f"Malformed command JSON: {e}")
                except Exception as e:
                    _handle_cmd_error(cmd_file, f"Command processing error: {e}")
        except Exception:
            logger.exception("Error in monitor_commands loop")
        _stop_event.wait(0.1)


# =============================================================================
# HANDLER REGISTRY — Maps tool names to handler functions
# =============================================================================


def execute_command(command):
    global app
    tool_name = command.get("name")
    params = command.get("params", {})
    try:
        design = app.activeProduct
        if not design:
            return {"success": False, "error": "No active design"}
        rootComp = design.rootComponent

        handler = HANDLER_REGISTRY.get(tool_name)
        if handler is None:
            return {"success": False, "error": f"Unknown tool: {tool_name}"}
        return handler(design, rootComp, params)
    except Exception as e:
        logger.exception("Handler %s failed", tool_name)
        return {"success": False, "error": str(e)}


# =============================================================================
# SHARED HELPERS
# =============================================================================

# Safe directories for export/import (same list as MCP server)
# SYNC: Keep in sync with mcp-server/validation.py SAFE_EXPORT_DIRS
_SAFE_EXPORT_DIRS = [
    (Path.home() / "Desktop").resolve(),
    (Path.home() / "Downloads").resolve(),
    (Path.home() / "Documents").resolve(),
]


def _validate_export_path(filepath):
    """Validate export/import filepath is within safe directories."""
    if not filepath or not filepath.strip():
        return None, {"success": False, "error": "Filepath cannot be empty"}
    if "\x00" in filepath:
        return None, {"success": False, "error": "Filepath contains null bytes"}
    resolved = Path(filepath).expanduser().resolve()
    is_safe = any(resolved.is_relative_to(d) for d in _SAFE_EXPORT_DIRS)
    if not is_safe:
        return None, {"success": False, "error": "Filepath outside allowed directories (~/Desktop, ~/Downloads, ~/Documents)"}
    return str(resolved), None


def _get_active_sketch(design):
    """Get the active sketch or return an error dict."""
    activeEdit = design.activeEditObject
    if not activeEdit:
        return None, {"success": False, "error": "No active sketch"}
    if not isinstance(activeEdit, adsk.fusion.Sketch):
        return None, {"success": False, "error": "Active edit context is not a sketch. Call finish_sketch or close the active editor first."}
    return activeEdit, None


def _collect_edges(body, indices=None):
    """Collect edges by index list, or all edges if indices is None."""
    edges = adsk.core.ObjectCollection.create()
    if indices is not None:
        for idx in indices:
            if idx < 0 or idx >= body.edges.count:
                return None, {"success": False, "error": f"Invalid edge index: {idx}. Available: 0-{body.edges.count - 1}"}
            edges.add(body.edges.item(idx))
    else:
        for edge in body.edges:
            edges.add(edge)
    return edges, None


def _collect_faces(body, indices=None):
    """Collect faces by index list, or all faces if indices is None."""
    faces = adsk.core.ObjectCollection.create()
    if indices is not None:
        for idx in indices:
            if idx < 0 or idx >= body.faces.count:
                return None, {"success": False, "error": f"Invalid face index: {idx}. Available: 0-{body.faces.count - 1}"}
            faces.add(body.faces.item(idx))
    else:
        for face in body.faces:
            faces.add(face)
    return faces, None


def _get_joint(rootComp, params):
    """Get a joint by index or return an error dict."""
    joint_index = params.get("joint_index", 0)
    if joint_index < 0 or joint_index >= rootComp.joints.count:
        return None, {"success": False, "error": f"Invalid joint_index: {joint_index}. Available: 0-{rootComp.joints.count - 1}"}
    return rootComp.joints.item(joint_index), None


# =============================================================================
# SKETCH HANDLERS
# =============================================================================


def handle_create_sketch(design, rootComp, params):
    plane_name = params.get("plane", "XY")
    offset = params.get("offset", 0)
    plane_map = {
        "XY": rootComp.xYConstructionPlane,
        "XZ": rootComp.xZConstructionPlane,
        "YZ": rootComp.yZConstructionPlane,
    }
    plane = plane_map.get(plane_name)
    if plane is None:
        return {"success": False, "error": f"Invalid plane: {plane_name}. Must be XY, XZ, or YZ"}

    if offset != 0:
        planes = rootComp.constructionPlanes
        planeInput = planes.createInput()
        offsetVal = adsk.core.ValueInput.createByReal(offset)
        planeInput.setByOffset(plane, offsetVal)
        plane = planes.add(planeInput)

    sketch = rootComp.sketches.add(plane)
    return {"success": True, "sketch_name": sketch.name}


def handle_draw_circle(design, rootComp, params):
    sketch, err = _get_active_sketch(design)
    if err:
        return err
    center = adsk.core.Point3D.create(params["center_x"], params["center_y"], 0)
    sketch.sketchCurves.sketchCircles.addByCenterRadius(center, params["radius"])
    return {"success": True}


def handle_draw_rectangle(design, rootComp, params):
    sketch, err = _get_active_sketch(design)
    if err:
        return err
    p1 = adsk.core.Point3D.create(params["x1"], params["y1"], 0)
    p2 = adsk.core.Point3D.create(params["x2"], params["y2"], 0)
    sketch.sketchCurves.sketchLines.addTwoPointRectangle(p1, p2)
    return {"success": True}


def handle_extrude(design, rootComp, params):
    if rootComp.sketches.count == 0:
        return {"success": False, "error": "No sketches"}
    sketch = rootComp.sketches.item(rootComp.sketches.count - 1)
    if sketch.profiles.count == 0:
        return {"success": False, "error": "No profiles"}

    profile_index = params.get("profile_index", 0)
    if profile_index < 0 or profile_index >= sketch.profiles.count:
        return {"success": False, "error": f"Invalid profile_index: {profile_index}. Available: 0-{sketch.profiles.count - 1}"}
    profile = sketch.profiles.item(profile_index)

    extrudes = rootComp.features.extrudeFeatures
    extInput = extrudes.createInput(profile, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
    extInput.setDistanceExtent(False, adsk.core.ValueInput.createByReal(params["distance"]))

    taper_angle = params.get("taper_angle", 0)
    if taper_angle != 0:
        extInput.taperAngle = adsk.core.ValueInput.createByReal(math.radians(taper_angle))

    extrude = extrudes.add(extInput)
    return {"success": True, "feature_name": extrude.name}


def handle_revolve(design, rootComp, params):
    if rootComp.sketches.count == 0:
        return {"success": False, "error": "No sketches"}
    sketch = rootComp.sketches.item(rootComp.sketches.count - 1)
    if sketch.profiles.count == 0:
        return {"success": False, "error": "No profiles"}
    profile = sketch.profiles.item(sketch.profiles.count - 1)
    axis_name = params.get("axis", "Y").upper()
    axis_map = {
        "X": rootComp.xConstructionAxis,
        "Y": rootComp.yConstructionAxis,
        "Z": rootComp.zConstructionAxis,
    }
    axis = axis_map.get(axis_name)
    if axis is None:
        return {"success": False, "error": f"Invalid axis: '{axis_name}'. Must be X, Y, or Z"}
    revolves = rootComp.features.revolveFeatures
    revInput = revolves.createInput(profile, axis, adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
    revInput.setAngleExtent(False, adsk.core.ValueInput.createByReal(math.radians(params["angle"])))
    revolve = revolves.add(revInput)
    return {"success": True, "feature_name": revolve.name}


def handle_fillet(design, rootComp, params):
    body, err = _get_body(rootComp, params)
    if err:
        return err
    edges, err = _collect_edges(body, params.get("edges"))
    if err:
        return err

    fillets = rootComp.features.filletFeatures
    filletInput = fillets.createInput()
    filletInput.addConstantRadiusEdgeSet(edges, adsk.core.ValueInput.createByReal(params["radius"]), True)
    fillet = fillets.add(filletInput)
    return {"success": True, "feature_name": fillet.name}


def handle_finish_sketch(design, rootComp, params):
    rootComp.activate()
    return {"success": True, "message": "Sketch finished"}


def handle_fit_view(design, rootComp, params):
    global app
    app.activeViewport.fit()
    return {"success": True}


def handle_get_design_info(design, rootComp, params):
    return {
        "success": True,
        "design_name": design.parentDocument.name,
        "body_count": rootComp.bRepBodies.count,
        "sketch_count": rootComp.sketches.count,
        "component_count": rootComp.occurrences.count,
    }


# =============================================================================
# HANDLERS — Added in MT-1 audit
# =============================================================================


def _get_body(rootComp, params):
    """Helper: resolve body from params. Returns (body, error_dict_or_None)."""
    body_index = params.get("body_index")
    if body_index is not None:
        if body_index < 0 or body_index >= rootComp.bRepBodies.count:
            return None, {"success": False, "error": f"Invalid body_index: {body_index}. Available: 0-{rootComp.bRepBodies.count - 1}"}
        return rootComp.bRepBodies.item(body_index), None
    if rootComp.bRepBodies.count == 0:
        return None, {"success": False, "error": "No bodies in design"}
    return rootComp.bRepBodies.item(rootComp.bRepBodies.count - 1), None


def handle_draw_line(design, rootComp, params):
    sketch, err = _get_active_sketch(design)
    if err:
        return err
    p1 = adsk.core.Point3D.create(params["x1"], params["y1"], 0)
    p2 = adsk.core.Point3D.create(params["x2"], params["y2"], 0)
    sketch.sketchCurves.sketchLines.addByTwoPoints(p1, p2)
    return {"success": True}


def handle_draw_arc(design, rootComp, params):
    sketch, err = _get_active_sketch(design)
    if err:
        return err
    center = adsk.core.Point3D.create(params["center_x"], params["center_y"], 0)
    start = adsk.core.Point3D.create(params["start_x"], params["start_y"], 0)
    sweep = math.atan2(params["end_y"] - params["center_y"], params["end_x"] - params["center_x"]) - math.atan2(
        params["start_y"] - params["center_y"], params["start_x"] - params["center_x"]
    )
    if abs(sweep) < 1e-6:
        return {"success": False, "error": "Degenerate arc: start and end points are coincident (or nearly so)"}
    if sweep <= 0:
        sweep += 2 * math.pi
    sketch.sketchCurves.sketchArcs.addByCenterStartSweep(center, start, sweep)
    return {"success": True}


def handle_draw_polygon(design, rootComp, params):
    sketch, err = _get_active_sketch(design)
    if err:
        return err
    center = adsk.core.Point3D.create(params["center_x"], params["center_y"], 0)
    vertex = adsk.core.Point3D.create(params["center_x"] + params["radius"], params["center_y"], 0)
    sides = params.get("sides", 6)
    sketch.sketchCurves.sketchLines.addCenterPointPolygon(center, vertex, sides)
    return {"success": True}


def handle_chamfer(design, rootComp, params):
    body, err = _get_body(rootComp, params)
    if err:
        return err
    edges, err = _collect_edges(body, params.get("edges"))
    if err:
        return err

    chamfers = rootComp.features.chamferFeatures
    chamferInput = chamfers.createInput2()
    chamferInput.chamferEdgeSets.addEqualDistanceChamferEdgeSet(edges, adsk.core.ValueInput.createByReal(params["distance"]), True)
    chamfer = chamfers.add(chamferInput)
    return {"success": True, "feature_name": chamfer.name}


def handle_shell(design, rootComp, params):
    body, err = _get_body(rootComp, params)
    if err:
        return err

    faces, err = _collect_faces(body, params.get("faces_to_remove"))
    if err:
        return err

    shells = rootComp.features.shellFeatures
    isTangentChain = False
    shellInput = shells.createInput([body], isTangentChain)
    shellInput.insideThickness = adsk.core.ValueInput.createByReal(params["thickness"])
    if faces.count > 0:
        shellInput.removedFaces = faces
    shell = shells.add(shellInput)
    return {"success": True, "feature_name": shell.name}


def handle_draft(design, rootComp, params):
    body, err = _get_body(rootComp, params)
    if err:
        return err

    face_coll, err = _collect_faces(body, params.get("faces"))
    if err:
        return err

    pull_dir = adsk.core.Vector3D.create(params.get("pull_x", 0), params.get("pull_y", 0), params.get("pull_z", 1))
    plane = adsk.core.Plane.create(adsk.core.Point3D.create(0, 0, 0), pull_dir)

    drafts = rootComp.features.draftFeatures
    draftInput = drafts.createInput(face_coll, plane, False)
    draftInput.angle = adsk.core.ValueInput.createByReal(math.radians(params["angle"]))
    draft = drafts.add(draftInput)
    return {"success": True, "feature_name": draft.name}


def handle_combine(design, rootComp, params):
    target_idx = params["target_body"]
    tool_indices = params["tool_bodies"]
    operation_name = params.get("operation", "cut")
    keep_tools = params.get("keep_tools", False)

    if rootComp.bRepBodies.count == 0:
        return {"success": False, "error": "No bodies in design"}

    ops_map = {
        "cut": adsk.fusion.FeatureOperations.CutFeatureOperation,
        "join": adsk.fusion.FeatureOperations.JoinFeatureOperation,
        "intersect": adsk.fusion.FeatureOperations.IntersectFeatureOperation,
    }
    op = ops_map.get(operation_name)
    if op is None:
        return {"success": False, "error": f"Invalid operation: {operation_name}. Must be cut, join, or intersect"}

    if target_idx < 0 or target_idx >= rootComp.bRepBodies.count:
        return {"success": False, "error": f"Invalid target_body: {target_idx}"}

    target = rootComp.bRepBodies.item(target_idx)
    tools = adsk.core.ObjectCollection.create()
    for idx in tool_indices:
        if idx < 0 or idx >= rootComp.bRepBodies.count:
            return {"success": False, "error": f"Invalid tool body index: {idx}"}
        tools.add(rootComp.bRepBodies.item(idx))

    combines = rootComp.features.combineFeatures
    combineInput = combines.createInput(target, tools)
    combineInput.operation = op
    combineInput.isKeepToolBodies = keep_tools
    combine = combines.add(combineInput)
    return {"success": True, "feature_name": combine.name}


def handle_pattern_rectangular(design, rootComp, params):
    body, err = _get_body(rootComp, params)
    if err:
        return err

    entities = adsk.core.ObjectCollection.create()
    entities.add(body)

    x_axis = rootComp.xConstructionAxis
    y_axis = rootComp.yConstructionAxis

    patterns = rootComp.features.rectangularPatternFeatures
    patInput = patterns.createInput(entities, x_axis)
    patInput.quantityOne = adsk.core.ValueInput.createByString(str(params["x_count"]))
    patInput.distanceOne = adsk.core.ValueInput.createByReal(params["x_spacing"] * (params["x_count"] - 1))

    if params.get("y_count", 1) > 1:
        patInput.setDirectionTwo(y_axis)
        patInput.quantityTwo = adsk.core.ValueInput.createByString(str(params["y_count"]))
        patInput.distanceTwo = adsk.core.ValueInput.createByReal(params["y_spacing"] * (params["y_count"] - 1))

    pattern = patterns.add(patInput)
    return {"success": True, "feature_name": pattern.name}


def handle_pattern_circular(design, rootComp, params):
    body, err = _get_body(rootComp, params)
    if err:
        return err

    entities = adsk.core.ObjectCollection.create()
    entities.add(body)

    axis_map = {
        "X": rootComp.xConstructionAxis,
        "Y": rootComp.yConstructionAxis,
        "Z": rootComp.zConstructionAxis,
    }
    axis_name = params.get("axis", "Z")
    axis = axis_map.get(axis_name)
    if axis is None:
        return {"success": False, "error": f"Invalid axis: {axis_name}. Must be X, Y, or Z"}

    patterns = rootComp.features.circularPatternFeatures
    patInput = patterns.createInput(entities, axis)
    patInput.quantity = adsk.core.ValueInput.createByString(str(params["count"]))
    patInput.totalAngle = adsk.core.ValueInput.createByReal(math.radians(params.get("angle", 360)))
    pattern = patterns.add(patInput)
    return {"success": True, "feature_name": pattern.name}


def handle_mirror(design, rootComp, params):
    body, err = _get_body(rootComp, params)
    if err:
        return err

    entities = adsk.core.ObjectCollection.create()
    entities.add(body)

    plane_map = {
        "XY": rootComp.xYConstructionPlane,
        "XZ": rootComp.xZConstructionPlane,
        "YZ": rootComp.yZConstructionPlane,
    }
    plane_name = params.get("plane", "YZ")
    plane = plane_map.get(plane_name)
    if plane is None:
        return {"success": False, "error": f"Invalid plane: {plane_name}. Must be XY, XZ, or YZ"}

    mirrors = rootComp.features.mirrorFeatures
    mirInput = mirrors.createInput(entities, plane)
    mirror = mirrors.add(mirInput)
    return {"success": True, "feature_name": mirror.name}


def handle_get_body_info(design, rootComp, params):
    body, err = _get_body(rootComp, params)
    if err:
        return err

    edges_info = []
    for i in range(body.edges.count):
        edge = body.edges.item(i)
        edges_info.append({"index": i, "length": round(edge.length, 4)})

    faces_info = []
    for i in range(body.faces.count):
        face = body.faces.item(i)
        faces_info.append({"index": i, "area": round(face.area, 4)})

    bb = body.boundingBox
    return {
        "success": True,
        "body_name": body.name,
        "edge_count": body.edges.count,
        "face_count": body.faces.count,
        "edges": edges_info,
        "faces": faces_info,
        "bounding_box": {
            "min": {"x": round(bb.minPoint.x, 4), "y": round(bb.minPoint.y, 4), "z": round(bb.minPoint.z, 4)},
            "max": {"x": round(bb.maxPoint.x, 4), "y": round(bb.maxPoint.y, 4), "z": round(bb.maxPoint.z, 4)},
        },
    }


def handle_measure(design, rootComp, params):
    measure_type = params.get("type", "body")
    body, err = _get_body(rootComp, params)
    if err:
        return err

    if measure_type == "body":
        props = body.physicalProperties
        bb = body.boundingBox
        return {
            "success": True,
            "volume": round(props.volume, 6),
            "surface_area": round(props.area, 6),
            "bounding_box": {
                "size_x": round(bb.maxPoint.x - bb.minPoint.x, 4),
                "size_y": round(bb.maxPoint.y - bb.minPoint.y, 4),
                "size_z": round(bb.maxPoint.z - bb.minPoint.z, 4),
            },
        }
    elif measure_type == "edge":
        edge_index = params.get("edge_index", 0)
        if edge_index < 0 or edge_index >= body.edges.count:
            return {"success": False, "error": f"Invalid edge_index: {edge_index}"}
        edge = body.edges.item(edge_index)
        return {"success": True, "length": round(edge.length, 4)}
    elif measure_type == "face":
        face_index = params.get("face_index", 0)
        if face_index < 0 or face_index >= body.faces.count:
            return {"success": False, "error": f"Invalid face_index: {face_index}"}
        face = body.faces.item(face_index)
        return {"success": True, "area": round(face.area, 4)}
    else:
        return {"success": False, "error": f"Invalid type: {measure_type}. Must be body, edge, or face"}


def handle_create_component(design, rootComp, params):
    if rootComp.bRepBodies.count == 0:
        return {"success": False, "error": "No bodies to convert"}
    body = rootComp.bRepBodies.item(rootComp.bRepBodies.count - 1)
    occ = rootComp.occurrences.addNewComponent(adsk.core.Matrix3D.create())
    comp = occ.component
    if params.get("name"):
        comp.name = params["name"]
    body.moveToComponent(occ)
    return {"success": True, "component_name": comp.name}


def handle_list_components(design, rootComp, params):
    components = []
    for i in range(rootComp.occurrences.count):
        occ = rootComp.occurrences.item(i)
        transform = occ.transform
        components.append({
            "index": i,
            "name": occ.component.name,
            "position": {
                "x": round(transform.translation.x, 4),
                "y": round(transform.translation.y, 4),
                "z": round(transform.translation.z, 4),
            },
        })
    return {"success": True, "components": components, "count": rootComp.occurrences.count}


def handle_delete_component(design, rootComp, params):
    name = params.get("name")
    index = params.get("index")

    if name:
        for i in range(rootComp.occurrences.count):
            occ = rootComp.occurrences.item(i)
            if occ.component.name == name:
                occ.deleteMe()
                return {"success": True, "deleted": name}
        return {"success": False, "error": f"Component '{name}' not found"}
    elif index is not None:
        if index < 0 or index >= rootComp.occurrences.count:
            return {"success": False, "error": f"Invalid index: {index}"}
        occ = rootComp.occurrences.item(index)
        comp_name = occ.component.name
        occ.deleteMe()
        return {"success": True, "deleted": comp_name}
    return {"success": False, "error": "Provide name or index"}


def handle_check_interference(design, rootComp, params):
    count = rootComp.occurrences.count
    if count < 2:
        return {"success": True, "interference": False, "message": "Need at least 2 components"}

    # Cache occurrences and bounding boxes upfront to avoid O(n²) COM calls
    occs = [(rootComp.occurrences.item(i), rootComp.occurrences.item(i).boundingBox) for i in range(count)]

    results = []
    for i, (occ1, bb1) in enumerate(occs):
        for occ2, bb2 in occs[i + 1:]:
            overlaps = (
                bb1.minPoint.x <= bb2.maxPoint.x
                and bb1.maxPoint.x >= bb2.minPoint.x
                and bb1.minPoint.y <= bb2.maxPoint.y
                and bb1.maxPoint.y >= bb2.minPoint.y
                and bb1.minPoint.z <= bb2.maxPoint.z
                and bb1.maxPoint.z >= bb2.minPoint.z
            )
            if overlaps:
                results.append({"component1": occ1.component.name, "component2": occ2.component.name})

    return {"success": True, "interference": len(results) > 0, "pairs": results}


def handle_move_component(design, rootComp, params):
    occ = _resolve_component(rootComp, params)
    if isinstance(occ, dict):
        return occ

    transform = occ.transform
    if params.get("absolute", True):
        transform.translation = adsk.core.Vector3D.create(params.get("x", 0), params.get("y", 0), params.get("z", 0))
    else:
        current = transform.translation
        transform.translation = adsk.core.Vector3D.create(
            current.x + params.get("x", 0), current.y + params.get("y", 0), current.z + params.get("z", 0)
        )
    occ.transform = transform
    design.snapshots.add()
    return {"success": True, "component": occ.component.name}


def handle_rotate_component(design, rootComp, params):
    occ = _resolve_component(rootComp, params)
    if isinstance(occ, dict):
        return occ

    axis_map = {
        "X": adsk.core.Vector3D.create(1, 0, 0),
        "Y": adsk.core.Vector3D.create(0, 1, 0),
        "Z": adsk.core.Vector3D.create(0, 0, 1),
    }
    axis_name = params.get("axis", "Z")
    axis_vec = axis_map.get(axis_name)
    if axis_vec is None:
        return {"success": False, "error": f"Invalid axis: {axis_name}. Must be X, Y, or Z"}

    origin = adsk.core.Point3D.create(params.get("origin_x", 0), params.get("origin_y", 0), params.get("origin_z", 0))
    rotation = adsk.core.Matrix3D.create()
    rotation.setToRotation(math.radians(params["angle"]), axis_vec, origin)
    transform = occ.transform
    transform.transformBy(rotation)
    occ.transform = transform
    design.snapshots.add()
    return {"success": True, "component": occ.component.name}


def _resolve_component(rootComp, params):
    """Helper: resolve component occurrence from params. Returns occ or error dict."""
    name = params.get("name")
    index = params.get("index")

    if name:
        for i in range(rootComp.occurrences.count):
            occ = rootComp.occurrences.item(i)
            if occ.component.name == name:
                return occ
        return {"success": False, "error": f"Component '{name}' not found"}
    elif index is not None:
        if index < 0 or index >= rootComp.occurrences.count:
            return {"success": False, "error": f"Invalid component index: {index}"}
        return rootComp.occurrences.item(index)
    return {"success": False, "error": "Provide component name or index"}


def _resolve_two_components(rootComp, params):
    """Resolve two component occurrences for joint creation."""
    idx1 = params.get("component1_index", 0)
    idx2 = params.get("component2_index", 1)
    count = rootComp.occurrences.count
    if count < 2:
        return None, None, {"success": False, "error": f"Need at least 2 component occurrences (found {count})"}
    if idx1 < 0 or idx1 >= count:
        return None, None, {"success": False, "error": f"Invalid component1_index: {idx1}. Available: 0-{count - 1}"}
    if idx2 < 0 or idx2 >= count:
        return None, None, {"success": False, "error": f"Invalid component2_index: {idx2}. Available: 0-{count - 1}"}
    if idx1 == idx2:
        return None, None, {"success": False, "error": "component1_index and component2_index must be different"}
    return rootComp.occurrences.item(idx1), rootComp.occurrences.item(idx2), None


def handle_create_revolute_joint(design, rootComp, params):
    occ1, occ2, err = _resolve_two_components(rootComp, params)
    if err:
        return err
    joints = rootComp.joints
    point = adsk.core.Point3D.create(params.get("x", 0), params.get("y", 0), params.get("z", 0))
    geo1 = adsk.fusion.JointGeometry.createByPoint(occ1, point)
    geo2 = adsk.fusion.JointGeometry.createByPoint(occ2, point)
    jointInput = joints.createInput(geo1, geo2)
    jointInput.setAsRevoluteJointMotion(adsk.fusion.JointDirections.ZAxisJointDirection)
    joint = joints.add(jointInput)
    return {"success": True, "joint_name": joint.name}


def handle_create_slider_joint(design, rootComp, params):
    occ1, occ2, err = _resolve_two_components(rootComp, params)
    if err:
        return err
    joints = rootComp.joints
    point = adsk.core.Point3D.create(params.get("x", 0), params.get("y", 0), params.get("z", 0))
    geo1 = adsk.fusion.JointGeometry.createByPoint(occ1, point)
    geo2 = adsk.fusion.JointGeometry.createByPoint(occ2, point)
    jointInput = joints.createInput(geo1, geo2)
    jointInput.setAsSliderJointMotion(adsk.fusion.JointDirections.XAxisJointDirection)
    joint = joints.add(jointInput)
    return {"success": True, "joint_name": joint.name}


def handle_set_joint_angle(design, rootComp, params):
    joint, err = _get_joint(rootComp, params)
    if err:
        return err
    motion = joint.jointMotion
    motion.rotationValue = math.radians(params["angle"])
    return {"success": True, "joint_name": joint.name, "angle": params["angle"]}


def handle_set_joint_distance(design, rootComp, params):
    joint, err = _get_joint(rootComp, params)
    if err:
        return err
    motion = joint.jointMotion
    motion.slideValue = params["distance"]
    return {"success": True, "joint_name": joint.name, "distance": params["distance"]}


def handle_undo(design, rootComp, params):
    global app
    count = min(params.get("count", 1), 10)  # Cap at 10 to prevent bulk destruction
    if count < 1:
        return {"success": False, "error": "count must be at least 1"}
    undone = 0
    for _ in range(count):
        if app.executeTextCommand("Commands.Undo"):
            undone += 1
        else:
            break
    return {"success": True, "undone_count": undone}


def handle_delete_body(design, rootComp, params):
    body, err = _get_body(rootComp, params)
    if err:
        return err
    body_name = body.name
    body.deleteMe()
    return {"success": True, "deleted": body_name}


def handle_delete_sketch(design, rootComp, params):
    sketch_index = params.get("sketch_index")
    if sketch_index is not None:
        if sketch_index < 0 or sketch_index >= rootComp.sketches.count:
            return {"success": False, "error": f"Invalid sketch_index: {sketch_index}"}
        sketch = rootComp.sketches.item(sketch_index)
    else:
        if rootComp.sketches.count == 0:
            return {"success": False, "error": "No sketches to delete"}
        sketch = rootComp.sketches.item(rootComp.sketches.count - 1)
    sketch_name = sketch.name
    sketch.deleteMe()
    return {"success": True, "deleted": sketch_name}


def handle_export_stl(design, rootComp, params):
    filepath, err = _validate_export_path(params.get("filepath", ""))
    if err:
        return err
    exportMgr = design.exportManager
    stlOpts = exportMgr.createSTLExportOptions(rootComp, filepath)
    exportMgr.execute(stlOpts)
    return {"success": True, "filepath": filepath}


def handle_export_step(design, rootComp, params):
    filepath, err = _validate_export_path(params.get("filepath", ""))
    if err:
        return err
    exportMgr = design.exportManager
    stepOpts = exportMgr.createSTEPExportOptions(filepath, rootComp)
    exportMgr.execute(stepOpts)
    return {"success": True, "filepath": filepath}


def handle_export_3mf(design, rootComp, params):
    filepath, err = _validate_export_path(params.get("filepath", ""))
    if err:
        return err
    exportMgr = design.exportManager
    opts = exportMgr.createC3MFExportOptions(rootComp, filepath)
    exportMgr.execute(opts)
    return {"success": True, "filepath": filepath}


def handle_import_mesh(design, rootComp, params):
    filepath, err = _validate_export_path(params.get("filepath", ""))
    if err:
        return err
    importMgr = app.importManager
    meshOpts = importMgr.createMeshImportOptions(filepath)
    unit_map = {"mm": adsk.core.DistanceUnits.MillimeterDistanceUnits, "cm": adsk.core.DistanceUnits.CentimeterDistanceUnits, "in": adsk.core.DistanceUnits.InchDistanceUnits}
    meshOpts.units = unit_map.get(params.get("unit", "mm"), adsk.core.DistanceUnits.MillimeterDistanceUnits)
    importMgr.importToTarget(meshOpts, rootComp)
    return {"success": True, "filepath": filepath}


MAX_BATCH_COMMANDS = 20


def handle_batch(design, rootComp, params):
    commands = params.get("commands", [])
    if len(commands) > MAX_BATCH_COMMANDS:
        return {"success": False, "error": f"Batch exceeds {MAX_BATCH_COMMANDS} commands (got {len(commands)})"}
    results = []
    for i, cmd in enumerate(commands):
        cmd_name = cmd.get("name")
        if cmd_name == "batch":
            return {"success": False, "error": "Nested batch commands are not allowed", "partial_results": results}
        cmd_params = cmd.get("params", {})
        handler = HANDLER_REGISTRY.get(cmd_name)
        if handler is None:
            return {"success": False, "error": f"Unknown tool in batch[{i}]: {cmd_name}", "partial_results": results}
        result = handler(design, rootComp, cmd_params)
        results.append(result)
        if not result.get("success"):
            return {"success": False, "error": f"Batch failed at step {i}: {result.get('error')}", "partial_results": results}
    return {"success": True, "results": results, "executed": len(results)}


# =============================================================================
# HANDLER REGISTRY
# =============================================================================

HANDLER_REGISTRY = {
    # Sketch creation
    "create_sketch": handle_create_sketch,
    "finish_sketch": handle_finish_sketch,
    # Sketch geometry
    "draw_rectangle": handle_draw_rectangle,
    "draw_circle": handle_draw_circle,
    "draw_line": handle_draw_line,
    "draw_arc": handle_draw_arc,
    "draw_polygon": handle_draw_polygon,
    # 3D features
    "extrude": handle_extrude,
    "revolve": handle_revolve,
    "fillet": handle_fillet,
    "chamfer": handle_chamfer,
    "shell": handle_shell,
    "draft": handle_draft,
    "combine": handle_combine,
    # Patterns
    "pattern_rectangular": handle_pattern_rectangular,
    "pattern_circular": handle_pattern_circular,
    "mirror": handle_mirror,
    # Inspection
    "get_design_info": handle_get_design_info,
    "get_body_info": handle_get_body_info,
    "measure": handle_measure,
    "fit_view": handle_fit_view,
    # Components
    "create_component": handle_create_component,
    "list_components": handle_list_components,
    "delete_component": handle_delete_component,
    "check_interference": handle_check_interference,
    "move_component": handle_move_component,
    "rotate_component": handle_rotate_component,
    # Joints
    "create_revolute_joint": handle_create_revolute_joint,
    "create_slider_joint": handle_create_slider_joint,
    "set_joint_angle": handle_set_joint_angle,
    "set_joint_distance": handle_set_joint_distance,
    # Utilities
    "undo": handle_undo,
    "delete_body": handle_delete_body,
    "delete_sketch": handle_delete_sketch,
    # Export/Import
    "export_stl": handle_export_stl,
    "export_step": handle_export_step,
    "export_3mf": handle_export_3mf,
    "import_mesh": handle_import_mesh,
    # Batch
    "batch": handle_batch,
}
